server:
  port: 9098

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

management:
  port: 9001
  security:
    enabled: false
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    shutdown:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

spring:
  application:
    name: school-service

logging:
  level:
    com.kodtodya.practice: DEBUG